%% Import data from text file.
function [Data,Label] = ImportFile(FileName)

% Script for importing data from the following text file:
%
%    /Users/sony/Dropbox/CS289Project/adult/adult_data.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/04/03 16:00:12

%% Initialize variables.
filename = ['/Users/sony/Dropbox/CS289Project/adult/' FileName '.txt'];
delimiter = ',';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: double (%f)
%	column4: text (%s)
%   column5: double (%f)
%	column6: text (%s)
%   column7: text (%s)
%	column8: text (%s)
%   column9: text (%s)
%	column10: text (%s)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: text (%s)
%   column15: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%s%f%s%f%s%s%s%s%s%f%f%f%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
data.AGE = dataArray{:, 1};
data.WORKCLASS = dataArray{:, 2};
data.FNLWGT = dataArray{:, 3};
data.EDUCATION = dataArray{:, 4};
data.EDUCATION_NUM = dataArray{:, 5};
data.MARTIAL = dataArray{:, 6};
data.OCCUPATION = dataArray{:, 7};
data.RELATIONSHIP = dataArray{:, 8};
data.RACE = dataArray{:, 9};
data.SEX = dataArray{:, 10};
data.CAPITAL_GAIN = dataArray{:, 11};
data.CAPITAL_LOSS = dataArray{:, 12};
data.HOURS_PER_WEEK = dataArray{:, 13};
data.NATIVE_COUNTRY = dataArray{:, 14};
data.LABEL = dataArray{:, 15};

Label = data.LABEL;
Data = rmfield(data,'LABEL');

for i = 1:length(Label) 
   if strcmp(Label{i},'<=50K') == true
       Label{i} = 0;  
   else
       Label{i} = 1;
   end
end
Label = cell2mat(Label);

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;